<a href="https://colab.research.google.com/github/Gopikanta/Machine-Learning---LAB/blob/main/Maths_of_Machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#define a vector
import numpy as np
list = [10, 20, 32]
vector = np.array(list)
print("We created a vector from list:", vector)


We created a vector from list: [10 20 32]


In [ ]:
#define a vector
import numpy as np
list = []
limit = 3
for i in range(limit):
  elements = int(input("Enter the elements:"))
  list.append(elements)
  vector = np.array(list)
print("We define a vector from list:", vector)

Enter the elements:34
Enter the elements:45
Enter the elements:23
We define a vector from list: [34 45 23]


In [ ]:
#add 2 vectors using numpy array
import numpy as np
list1 = [3, 5, 6]
list2 = [9, 2, 3]
vector1 = np.array(list1)
vector2 = np.array(list2)
vector = vector1 + vector2
print(vector)


[12  7  9]


In [ ]:
#add 2 numbers using numpyarary
import numpy as np
list1 = []
list2 = []
limit = int(input("Enter the limit:"))
for i in range(limit):
   elements1 = int(input("Enter the elements:"))
   list1.append(elements1)
print(list1)
for j in range(limit):
    elements2 = int(input("Enter the elements:"))
    list2.append(elements2)
print(list2)
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = np.add(vect1,vect2)
print("Sum of two vectors:", vect)


Enter the limit:4
Enter the elements:1
Enter the elements:2
Enter the elements:3
Enter the elements:4
[1, 2, 3, 4]
Enter the elements:4
Enter the elements:5
Enter the elements:6
Enter the elements:7
[4, 5, 6, 7]
Sum of two vectors: [ 5  7  9 11]


In [ ]:
#subtract two numbers
import numpy as np
list1 = [1, 2, 3]
list2 = [4, 5, 6]
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = vect1 - vect2
print(vect)

[-3 -3 -3]


In [ ]:
#take 2 vector as user input
#subtract
import numpy as np
list1 = []
list2 = []
limit = int(input("Enter the limit:"))
for i in range(limit):
    elements1 = int(input("Enter the elements:"))
    list1.append(elements1)
print(list1)
for j in range(limit):
    elements2 = int(input("Enter the elements:"))
    list2.append(elements2)
print(list2)
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = np.subtract(vect1,vect2)
print("Difference between two vectors", vect)


Enter the limit:3
Enter the elements:3
Enter the elements:2
Enter the elements:1
[3, 2, 1]
Enter the elements:2
Enter the elements:1
Enter the elements:1
[2, 1, 1]
Difference between two vectors [1 1 0]


In [ ]:
#multiply 2 vectors
import numpy as np
list1 = [2, 3, 4]
list2 = [3, 4, 5]
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = vect1 * vect2
print(vect)


[ 6 12 20]


In [ ]:
#multiply 2 numbers using vectors
import numpy as np
limit = int(input("Enter limit"))
list1 = []
list2 = []
for i in range(limit):
    elements1 = int(input("Enter elements:"))
    list1.append(elements1)
print(list1)
for j in range(limit):
    elements2 = int(input("Enter elements:"))
    list2.append(elements2)
print(list2)
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = np.multiply(vect1,vect2)
print("Division of two vectors;", vect)

Enter limit3
Enter elements:2
Enter elements:3
Enter elements:4
[2, 3, 4]
Enter elements:2
Enter elements:3
Enter elements:4
[2, 3, 4]
Division of two vectors; [ 4  9 16]


In [ ]:
#divide 2 vectors
import numpy as np
list1 = [2, 3, 4]
list2 = [3, 4, 5]
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = vect1 / vect2
print(vect)


[0.66666667 0.75       0.8       ]


In [ ]:
#divide 2 vectors(user)
import numpy as np
limit = int(input("Enter limit"))
list1 = []
list2 = []
for i in range(limit):
    elements1 = int(input("Enter elements:"))
    list1.append(elements1)
print(list1)
for j in range(limit):
    elements2 = int(input("Enter elements:"))
    list2.append(elements2)
print(list2)
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = np.divide(vect1,vect2)
print("Division of two vectors;", vect)

Enter limit3
Enter elements:2
Enter elements:3
Enter elements:4
[2, 3, 4]
Enter elements:2
Enter elements:3
Enter elements:4
[2, 3, 4]
Division of two vectors; [1. 1. 1.]


In [ ]:
#dot product
import numpy as np
list1 = [10, 20, 30, 40, 50]
list2 = [2, 4, 6, 8, 10]
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = vect1.dot(vect2)
print("Dot product", vect)

Dot product 1100


In [ ]:
#dot product
import numpy as np
list1 = []
list2 = []
limit = int(input("Enter the limit:"))
for i in range(limit):
    elements1 = int(input("Enter the elements:"))
    list1.append(elements1)
print(list1)
for j in range(limit):
    elements2 = int(input("Enter the elements:"))
    list2.append(elements2)
print(list2)
vect1 = np.array(list1)
vect2 = np.array(list2)
vect = vect1.dot(vect2)
print(vect)

Enter the limit:3
Enter the elements:2
Enter the elements:4
Enter the elements:6
[2, 4, 6]
Enter the elements:2
Enter the elements:4
Enter the elements:6
[2, 4, 6]
56


In [ ]:
#vectorscalar multiplication
import numpy as np
list1 = [10, 20, 30]
scalar = [2]
vect1 = np.array(list1)
vect2 = np.array(scalar)
vect = vect2*(vect1)
print("Vector scalar form:", vect)


Vector scalar form: [20 40 60]


In [ ]:
#vector scalar multiplication
import numpy as np
array1 = []
b = []
limit = int(input("Enter the limit:"))
for i in range (limit):
  elements = int(input("Enter the elements"))
  array1.append(elements)
print(array1)
b = int(input("Enter a number:"))
array =  * b
print(vect)

Enter the limit:3
Enter the elements1
Enter the elements2
Enter the elements3
[1, 2, 3]
Enter a number:2
[1, 2, 3, 1, 2, 3]


In [ ]:
#L1 norm
from numpy import array
from numpy . linalg import norm
arr = array([1, 2, 3])
L1 = norm(arr, 1)
print(L1)

6.0


In [ ]:

#L1 norm
from numpy import array
from numpy . linalg import norm
array = []
b = []
limit = int(input("Enter the limit:"))
for i in range(limit):
   elements = int(input("Enter the elements:"))
   array.append(elements)
print(array)
b = int(input("Enter the value"))
L1 = norm(array,b)
print(L1)





Enter the limit:5
Enter the elements:1
Enter the elements:2
Enter the elements:3
Enter the elements:4
Enter the elements:5
[1, 2, 3, 4, 5]
Enter the value1
15.0


In [ ]:
#L2 norm
from numpy import array
from numpy . linalg import norm
arr = array([1, 2, 3, 4, 5])
print(arr)
L2 = norm(arr,2)
print(L2)

[1 2 3 4 5]
7.416198487095663


In [ ]:
#L2 norm
from numpy import array
from numpy . linalg import norm
array = []
b = 2
limit = int(input("Enter a limit: "))
for i in range(limit):
    elements = int(input("Enter the elements: "))
    array.append(elements)
print(array)

L2 = norm(array,b)
print(L2)




Enter a limit: 5
Enter the elements: 1
Enter the elements: 2
Enter the elements: 3
Enter the elements: 4
Enter the elements: 5
[1, 2, 3, 4, 5]
7.416198487095663
